# conda env create environment.yml
name: castf90
channels:
  - birdhouse
  - conda-forge
dependencies:
  - python=2
  - gcc
  - libgfortran
  - mkl
  - mkl-service
  - openblas
  - lapack95
  - netcdf-fortran >=4.4.4
  - cdo
  - nco
